# Generated by Django 2.2.3 on 2019-07-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('repository', models.URLField(unique=True)),
                ('deploy_script', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('repository', models.URLField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=24, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=16, null=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('prerelease', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEN', 'PENDING'), ('DNG', 'DOING'), ('OK', 'DONE'), ('KO', 'ERROR')], max_length=16)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webhooks.Application')),
            ],
        ),
    ]
