# Generated by Django 2.2.3 on 2019-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('github_name', models.CharField(max_length=32, unique=True)),
                ('deploy_script', models.FilePathField()),
            ],
        ),
    ]
