# Generated by Django 2.2.3 on 2019-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20190709_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='action',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='author',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='prerelease',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
