# Generated by Django 2.2.3 on 2019-07-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20190709_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Application'),
        ),
    ]
