# Generated by Django 2.2.3 on 2019-07-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20190709_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='repository',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEN', 'PENDING'), ('DNG', 'DOING'), ('OK', 'DONE'), ('KO', 'ERROR')], max_length=16)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Application')),
                ('webhook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.WebHook')),
            ],
        ),
    ]
