# Generated by Django 2.2.3 on 2019-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20190709_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='application',
        ),
        migrations.AddField(
            model_name='webhook',
            name='repository',
            field=models.URLField(blank=True, null=True),
        ),
    ]
