# Generated by Django 2.2.3 on 2019-07-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_deploy_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deploy_script',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
