# Generated by Django 2.2.3 on 2019-07-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20190709_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='deploy_script',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
