# Generated by Django 2.2.3 on 2019-07-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
