# Generated by Django 2.2.3 on 2019-07-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20190725_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secret',
        ),
    ]
